### ISSUE TITLE
Child Nav Doesn't Expand on Hover

### ISSUE THREAD

**Issue by JQTNguyen** [badcamp/badcamp-2018#116]
Child Items in the Main Navigation only appear on Hover when on Parent/Sibling Page (e.g.: Sponsors > Sponsorship, Events > Summits, and Travel > Hotels).

**Comment by sean-e-dietrich** [comment]
@JQTNguyen I went through and enabled this but in the parent menu items `Show as expanded` should be checked.

**Comment by JQTNguyen** [comment]
Yup, I thought I checked this, but such is the bane of multitasking sometimes...  Derp.
