### ISSUE TITLE
Twitter Teaser

### ISSUE THREAD

**Issue by JQTNguyen** [badcamp/badcamp-2018#127]
For the "Session" Content Type, add a "Twitter Teaser" field with the following characteristics:

- [x] Plain text field
- [x] Limited to 240 characters
- [x] Does not appear on the Node Display
- [x] Has the following Help Text: "Provide a short teaser for your talk proposal that can be used for social media and proposed talk submissions. This field is limited to 240 characters."

**Comment by sean-e-dietrich** [comment]
Done
