### ISSUE TITLE
Volunteer form is not discoverable via the menus

### ISSUE THREAD

**Issue by torenware** [badcamp/badcamp-2018#151]
A volunteer for BADCamp webform exists at https://2018.badcamp.net/volunteer, and is anonymous/not-anonymous visible. It does *not*, however, appear on any of the menus (at least that I've found).  

I did check to make sure that the "I'd like to volunteer" checkbox is indeed implemented on the reg form -- it indeed is.

Minor issue discovered when I was looking for the volunteer form and did not find it.  Guessed the link, the link was right.

**Comment by JQTNguyen** [comment]
This has been resolved.
