### ISSUE TITLE
Format Issue on Event Reg Page

### ISSUE THREAD

**Issue by getrootid** [badcamp/badcamp-2018#159]
In Chrome, as a logged in user on the Event Registration page (https://2018.badcamp.net/registration/events) the "read more" buttons are getting cut off by the "thursday, October  25th" section title in the middle of the page.

<img width="908" alt="screen shot 2018-08-16 at 7 48 37 am" src="https://user-images.githubusercontent.com/2599895/44216254-5e24c800-a129-11e8-9a9f-71b153fb66df.png">

**Comment by JQTNguyen** [comment]
This should now be resolved.
