### ISSUE TITLE
Cost of "THEME DEVELOPMENT" training appears to be pegged at incorrect price ($25)

### ISSUE THREAD

**Issue by torenware** [badcamp/badcamp-2018#179]
I've noticed that the THEME DEVELOPMENT training, now reopened, is priced at $25. I checked the field, and discovered that it was indeed at 2500 for that field. Set it to 2000, and saved. We're still displaying $25.

Not sure if this is a caching artifact or a theming issue.  I tried logging on on Safari, and checked the price, and see that it is $25 there as well.

**Comment by sean-e-dietrich** [comment]
@torenware there is a description field that had $25 set manually.
