### ISSUE TITLE
UX - size on some splashpage text not responsive 

### ISSUE THREAD

**Issue by scalico** [badcamp/badcamp-2018#99]
UX - splashpage text not responsive 
in second section (with weight lifter), including gold bar just below.
Observed with IE 11 and Firefox 59.0.2.

**Comment by JQTNguyen** [comment]
This is referring to text size, and how some Text Size scales down (e.g.: "Join Us October 24-27..." gets smaller in size at smaller view ports), while others do not.

Text that is not scaling down includes: "About BADCamp" content area, Gold Bar content , Location content area.

**Comment by JQTNguyen** [comment]
I don't believe this addresses the original reported issue.  See attached screenshot, where affected areas are outlined.
<img width="524" alt="home___badcamp_2018" src="https://user-images.githubusercontent.com/3485338/38337430-07c7d27c-381a-11e8-96fb-3aeec7a23089.png">
